### ISSUE TITLE
something about hardware address

### ISSUE THREAD

**Issue by WilliamsCeng** [Blackhawk95/Mtech_Internship#1]
in sdk_result.cc, line 30,31
```
float *inpHW = (float *) 0x42000000;
float *resHW = (float *) 0x40000000;
```
I wonder how you can figure out these addresses?  
Looking forward to your reply and thanks for your attention.

**Comment by Blackhawk95** [comment]
I haven’t used vivado in a while so I might be wrong here, but I believe this address is visible when we connect BRAM/BRAM controller (in Vivado), we can set the offset address using address editor. 

I think u can get some help with this tutorial. 

https://m.youtube.com/playlist?list=PLo7bVbJhQ6qzK6ELKCm8H_WEzzcr5YXHC

Also thanks for checking this out. I was not expecting anyone other than myself to use it, else I could have documented it better.

**Comment by WilliamsCeng** [comment]
Thank you so much. 
You've done me a great favor.
I think it is answered in 
VIVADO HLS Training - BRAM interface #06 ( https://www.youtube.com/watch?v=BUVbKonhc2w&list=PLo7bVbJhQ6qzK6ELKCm8H_WEzzcr5YXHC&index=6).

1. HLS needs an BRAM to deliver its parameters
2. ZYNQ needs an AXI BRAM Controller to access that BRAM directly
3. Those addresses are visible once AXI BRAM Controller is introduced into the block design

**Comment by Blackhawk95** [comment]
That’s great
I guess that solved your problem.

Let me know if something else is troubling you.
Happy to help.
I am closing this issue :)
